---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'debian/**'
      - 'doc/**'
      - 'subprojects/**'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'debian/**'
      - 'doc/**'
      - 'subprojects/**'
    branches:
      - master

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            meson \
            ccache

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{github.job}}

      - name: Configure
        run: |
          meson setup \
            -Dauto_features=enabled \
            -Ddocumentation=disabled \
            --force-fallback-for=fmt \
            -Dwrap_mode=nofallback \
            output

      - name: Build
        run: ninja -C output -v
